#!/usr/bin/env python3


import sys
import python.distance as dist


def build(*args, **kwargs):
    dist.run(*args)


def learn(*args, **kwargs):
    raise NotImplementedError("Not implemented yet")


def search(*args, **kwargs):
    raise NotImplementedError("Not implemented yet")


def stats(*args, **kwargs):
    raise NotImplementedError("Not implemented yet")


commands = {"build": build, "learn": learn,
            "search": search, "stats": stats}

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in commands.keys():
        msg = 'Usage: nns <cmd> [options] args...\nWhere <cmd> is one of: '
        msg += ', '.join(str(x) for x in sorted(commands.keys()))
        sys.exit(msg)
    else:
        command = commands[sys.argv[1]]
        args = sys.argv[2:]
        command(args)
